### ISSUE TITLE
Wrong projection for ra values of a consterllation.

### ISSUE THREAD

**Issue by oxno2** [eleanorlutz/western_constellations_atlas_of_space#1]
Hi:
I want to draw a constellation of Hydra. However, the projection looks like to be wrong.

The problem might be that the ra values of some stars in Hydra are smaller than 180, and some are larger.

![7](https://user-images.githubusercontent.com/22302177/62839551-098b2e80-bc51-11e9-828c-c78de4866a9c.png)

If I add 180 to the ra values of stars in Hydra, I can avoid this problem, but the grid values of ra are all wrong. Are there any methods for me to correct the grid values?

![6](https://user-images.githubusercontent.com/22302177/62839517-8cf85000-bc50-11e9-8d3d-3a0a0fbe1af8.png)

Also, I want to know if there are any methods for me to rotate the projection. I plot the Ursa Major but the projection needs to be rotated by 90 degrees.

![8](https://user-images.githubusercontent.com/22302177/62839567-2e7fa180-bc51-11e9-9473-b4bcfe9bdf6c.png)

**Comment by eleanorlutz** [comment]
Sorry about the late response on this! For rotating the plot, I'm not sure of a way to do this in Cartopy. But if it just needs to be rotated by 90 degrees, I would probably save the output as a PDF or image and rotate it using another software, like Windows Photos or Apple Preview. 

For plotting Hydra, I'm not quite sure I understand the problem. If you pick a projection that cuts the globe open, like the one you're using in the very first image, then I don't think there's a way to avoid having the constellations on the edges from being cut off - that is just how that specific projection shows the data. If you use a different projection and center the map on Hydra, you should be able to get around the issue.
